version: '3.8'

services:
  web:
    container_name: channles-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c '
        cd mysite &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        # gunicorn -w 4 -b 0.0.0.0:8080 backend.wsgi:application
        python manage.py runserver 0.0.0.0:8080
      '
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    tty: true

  redis:
    container_name: redis-server
    image: redis:7
    ports:
      - 6379:6379